# Generated by Django 6.0.3 on 2026-04-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_city_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('processing', 'В обробці'), ('shipped', 'Відправлено'), ('delivered', 'Отримано'), ('canceled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
